# Generated by Django 5.0 on 2024-02-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_contactus_alter_register_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='password',
            new_name='lastname',
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
