# Generated by Django 5.0 on 2024-02-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_rename_password_contactus_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
